# action.yml
name: 'DNS Analysis'
description: 'Run DNS analysis scripts'
inputs:
  args:
    description: 'what to do'
    required: true
    default: 'env'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # TODO not going anywhere?
  args:
    - ${{ inputs.args }}
